.PHONY: clean All

All:
	@echo "----------Building project:[ compressVecExample - Release ]----------"
	@cd "compressVecExample" && "$(MAKE)" -f  "compressVecExample.mk"
clean:
	@echo "----------Cleaning project:[ compressVecExample - Release ]----------"
	@cd "compressVecExample" && "$(MAKE)" -f  "compressVecExample.mk" clean
